name = "redblacktree"
uuid = "c219aedc-8d17-4def-9a4f-8b59ceaa4ef7"
authors = ["Perttu Ranta-aho <perttu.ranta-aho@f-secure.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
